name: giphy_get
description: Pick EMOJI,STICKER or GIF from Giphy in pure dart code. Support Android,iOS,Web and Desktop.
version: 3.5.0
homepage: https://github.com/bazookon/giphy_get

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.0.5
  extended_image: ^8.2.0
  flutter_staggered_grid_view: ^0.7.0
  meta: ^1.9.1
  http: ^1.1.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.3
  pedantic: ^1.11.1
  matcher: ^0.12.15

flutter:
  assets:
    - assets/img/
